# Generated by Django 5.2.5 on 2025-08-14 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombres')),
                ('nacionality', models.CharField(blank=True, max_length=100, verbose_name='Nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('resume', models.TextField(blank=True, verbose_name='Resumen')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.author')),
            ],
        ),
    ]
